### ISSUE TITLE
Not compatible with Windows

### ISSUE THREAD

**Issue by abraaocaldas** [MichaelRocks/paranoid#1]
Hello, I´m trying to use it on Android Studio for windows, but I cannot because it generate a long path that windows don´t recognize.
On linux this problem do not occurs.

**Comment by MichaelRocks** [comment]
Hi @abraaocaldas, thank you for reporting the issue. I've just publish a new version 0.1.1 that should work fine on Windows. Unfortunately, I don't have Windows installed and cannot ensure if the issue is really fixed. It would be great if you can check the new version and tell me whether or not the issue is fixed.

**Comment by abraaocaldas** [comment]
Yep! It's working, thank you very much!
